name: Fetch Cryptocurrency Data

on:
  schedule:
    # Run every day at 2 AM UTC
    - cron: '0 2 * * *'
  # Allow manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  fetch-crypto-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create .env.local file
        run: |
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" > .env.local
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .env.local
          echo "COINGECKO_API_KEY=${{ secrets.COINGECKO_API_KEY }}" >> .env.local
      
      - name: Run data collection script
        run: python top100_supabase.py
      
