name: Daily Funding Indicator Update

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  
  # Allow manual triggering from the Actions tab
  workflow_dispatch:

jobs:
  update-funding-indicator:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install supabase pandas google-auth google-api-python-client plotly ta
        
    - name: Create funding credentials file
      run: echo '${{ secrets.FUNDING_CREDENTIALS_JSON }}' > funding-435016-442a60c70683.json
      
    - name: Run CI update script
      run: python ci_update_funding.py
      env:
        SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      
    - name: Log completion
      if: success()
      run: echo "Funding indicator has been updated successfully at $(date)"
      
    - name: Log failure
      if: failure()
      run: echo "Failed to update funding indicator at $(date)"
